/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    trainingDomains: TrainingDomain;
    partners: Partner;
    faq: Faq;
    programs: Program;
    events: Event;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    trainingDomains: TrainingDomainsSelect<false> | TrainingDomainsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homePage: HomePage;
    aboutPage: AboutPage;
    trainingsPage: TrainingsPage;
    contactPage: ContactPage;
    faqPage: FaqPage;
    programsPage: ProgramsPage;
    eventsPage: EventsPage;
  };
  globalsSelect: {
    homePage: HomePageSelect<false> | HomePageSelect<true>;
    aboutPage: AboutPageSelect<false> | AboutPageSelect<true>;
    trainingsPage: TrainingsPageSelect<false> | TrainingsPageSelect<true>;
    contactPage: ContactPageSelect<false> | ContactPageSelect<true>;
    faqPage: FaqPageSelect<false> | FaqPageSelect<true>;
    programsPage: ProgramsPageSelect<false> | ProgramsPageSelect<true>;
    eventsPage: EventsPageSelect<false> | EventsPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainingDomains".
 */
export interface TrainingDomain {
  id: number;
  name?: string | null;
  image?: (number | null) | Media;
  trainings?:
    | {
        name?: string | null;
        shortDescription?: string | null;
        longDescription?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        price?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  websiteUrl?: string | null;
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  name?: string | null;
  shortDescription?: string | null;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  status: 'upcoming' | 'past';
  date: string;
  time: string;
  location: string;
  image?: (number | null) | Media;
  shortDescription: string;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  registrationLink?: string | null;
  isRegistrationAvailable?: boolean | null;
  maximumParticipants?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'trainingDomains';
        value: number | TrainingDomain;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainingDomains_select".
 */
export interface TrainingDomainsSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  trainings?:
    | T
    | {
        name?: T;
        shortDescription?: T;
        longDescription?: T;
        price?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  websiteUrl?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  name?: T;
  shortDescription?: T;
  longDescription?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  date?: T;
  time?: T;
  location?: T;
  image?: T;
  shortDescription?: T;
  longDescription?: T;
  registrationLink?: T;
  isRegistrationAvailable?: T;
  maximumParticipants?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage".
 */
export interface HomePage {
  id: number;
  heroSection?: {
    /**
     * Ajoutez jusqu'à 3 images pour le slider de la section héro
     */
    heroImages?:
      | {
          heroImage?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    heroTitle?: string | null;
    heroSubtitle?: string | null;
    heroDescription?: string | null;
    heroPrimaryButtonText?: string | null;
    heroPrimaryButtonLink?: string | null;
    heroSecondaryButtonText?: string | null;
    heroSecondaryButtonLink?: string | null;
    /**
     * Statistiques affichées dans la section héro
     */
    heroStats?:
      | {
          value: string;
          label: string;
          icon: 'users' | 'graduation' | 'calendar';
          id?: string | null;
        }[]
      | null;
  };
  missionVisionSection?: {
    missionTitle?: string | null;
    missionHeading?: string | null;
    missionDescription?: string | null;
    missionDescription2?: string | null;
    visionTitle?: string | null;
    visionHeading?: string | null;
    visionDescription?: string | null;
    valuesTitle?: string | null;
    values?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  aboutUsSection?: {
    aboutUsSectionTitle?: string | null;
    aboutUsSectionSubtitle?: string | null;
    aboutUsSectionDescription?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    aboutUsSectionButtonText?: string | null;
    aboutUsSectionButtonLink?: string | null;
    aboutUsSectionImages?:
      | {
          image?: (number | null) | Media;
          alt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  statsSection?: {
    statsSectionEnabled?: boolean | null;
    statsSectionTitle?: string | null;
    statsSectionDescription?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          icon?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  partnersSection?: {
    ourPartnersSectionTitle?: string | null;
    ourPartnersSectionDescription?: string | null;
    partnersToShow?: (number | Partner)[] | null;
    showAllPartnersLink?: boolean | null;
    allPartnersLinkText?: string | null;
  };
  trainingsSection?: {
    ourTrainingsSectionTitle?: string | null;
    ourTrainingsSectionDescription?: string | null;
    trainingDomainsToFeature?: (number | TrainingDomain)[] | null;
    trainingsSectionButtonText?: string | null;
    trainingsSectionButtonLink?: string | null;
  };
  testimonialsSection?: {
    testimonialsSectionEnabled?: boolean | null;
    testimonialsSectionTitle?: string | null;
    testimonialsSectionDescription?: string | null;
    testimonials?:
      | {
          name: string;
          role?: string | null;
          content: string;
          photo?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  faqSection?: {
    faqSectionTitle?: string | null;
    faqSectionDescription?: string | null;
    frequentlyAskedQuestions?: (number | Faq)[] | null;
    faqSectionButtonText?: string | null;
    faqSectionButtonLink?: string | null;
  };
  contactSection?: {
    contactUsSectionTitle?: string | null;
    contactUsSectionDescription?: string | null;
    contactUsSectionImage?: (number | null) | Media;
    contactUsSectionButtonText?: string | null;
    contactUsSectionButtonLink?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage".
 */
export interface AboutPage {
  id: number;
  heroImage?: (number | null) | Media;
  heroTitle?: string | null;
  heroDescription?: string | null;
  heroButtonText?: string | null;
  aboutUsSectionTitle?: string | null;
  aboutUsSectionDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  aboutUsGallerySectionTitle?: string | null;
  aboutUsGallerySectionDescription?: string | null;
  aboutUsGallerySectionImages?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainingsPage".
 */
export interface TrainingsPage {
  id: number;
  heroImage?: (number | null) | Media;
  heroTitle?: string | null;
  heroDescription?: string | null;
  heroButtonText?: string | null;
  trainingsSectionTitle?: string | null;
  trainingsSectionDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPage".
 */
export interface ContactPage {
  id: number;
  heroImage?: (number | null) | Media;
  heroTitle?: string | null;
  heroDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqPage".
 */
export interface FaqPage {
  id: number;
  heroImage?: (number | null) | Media;
  heroTitle?: string | null;
  heroDescription?: string | null;
  heroButtonText?: string | null;
  faqSectionTitle?: string | null;
  faqSectionDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programsPage".
 */
export interface ProgramsPage {
  id: number;
  heroImage?: (number | null) | Media;
  heroTitle?: string | null;
  heroDescription?: string | null;
  heroButtonText?: string | null;
  programsSectionTitle?: string | null;
  programsSectionDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventsPage".
 */
export interface EventsPage {
  id: number;
  heroImage?: (number | null) | Media;
  heroTitle?: string | null;
  heroDescription?: string | null;
  upcomingEventsSectionTitle?: string | null;
  pastEventsSectionTitle?: string | null;
  ctaSectionTitle?: string | null;
  ctaSectionDescription?: string | null;
  proposeEventButtonText?: string | null;
  becomeSpeakerButtonText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroSection?:
    | T
    | {
        heroImages?:
          | T
          | {
              heroImage?: T;
              id?: T;
            };
        heroTitle?: T;
        heroSubtitle?: T;
        heroDescription?: T;
        heroPrimaryButtonText?: T;
        heroPrimaryButtonLink?: T;
        heroSecondaryButtonText?: T;
        heroSecondaryButtonLink?: T;
        heroStats?:
          | T
          | {
              value?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  missionVisionSection?:
    | T
    | {
        missionTitle?: T;
        missionHeading?: T;
        missionDescription?: T;
        missionDescription2?: T;
        visionTitle?: T;
        visionHeading?: T;
        visionDescription?: T;
        valuesTitle?: T;
        values?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  aboutUsSection?:
    | T
    | {
        aboutUsSectionTitle?: T;
        aboutUsSectionSubtitle?: T;
        aboutUsSectionDescription?: T;
        aboutUsSectionButtonText?: T;
        aboutUsSectionButtonLink?: T;
        aboutUsSectionImages?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
      };
  statsSection?:
    | T
    | {
        statsSectionEnabled?: T;
        statsSectionTitle?: T;
        statsSectionDescription?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  partnersSection?:
    | T
    | {
        ourPartnersSectionTitle?: T;
        ourPartnersSectionDescription?: T;
        partnersToShow?: T;
        showAllPartnersLink?: T;
        allPartnersLinkText?: T;
      };
  trainingsSection?:
    | T
    | {
        ourTrainingsSectionTitle?: T;
        ourTrainingsSectionDescription?: T;
        trainingDomainsToFeature?: T;
        trainingsSectionButtonText?: T;
        trainingsSectionButtonLink?: T;
      };
  testimonialsSection?:
    | T
    | {
        testimonialsSectionEnabled?: T;
        testimonialsSectionTitle?: T;
        testimonialsSectionDescription?: T;
        testimonials?:
          | T
          | {
              name?: T;
              role?: T;
              content?: T;
              photo?: T;
              id?: T;
            };
      };
  faqSection?:
    | T
    | {
        faqSectionTitle?: T;
        faqSectionDescription?: T;
        frequentlyAskedQuestions?: T;
        faqSectionButtonText?: T;
        faqSectionButtonLink?: T;
      };
  contactSection?:
    | T
    | {
        contactUsSectionTitle?: T;
        contactUsSectionDescription?: T;
        contactUsSectionImage?: T;
        contactUsSectionButtonText?: T;
        contactUsSectionButtonLink?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroImage?: T;
  heroTitle?: T;
  heroDescription?: T;
  heroButtonText?: T;
  aboutUsSectionTitle?: T;
  aboutUsSectionDescription?: T;
  aboutUsGallerySectionTitle?: T;
  aboutUsGallerySectionDescription?: T;
  aboutUsGallerySectionImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainingsPage_select".
 */
export interface TrainingsPageSelect<T extends boolean = true> {
  heroImage?: T;
  heroTitle?: T;
  heroDescription?: T;
  heroButtonText?: T;
  trainingsSectionTitle?: T;
  trainingsSectionDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPage_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  heroImage?: T;
  heroTitle?: T;
  heroDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqPage_select".
 */
export interface FaqPageSelect<T extends boolean = true> {
  heroImage?: T;
  heroTitle?: T;
  heroDescription?: T;
  heroButtonText?: T;
  faqSectionTitle?: T;
  faqSectionDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programsPage_select".
 */
export interface ProgramsPageSelect<T extends boolean = true> {
  heroImage?: T;
  heroTitle?: T;
  heroDescription?: T;
  heroButtonText?: T;
  programsSectionTitle?: T;
  programsSectionDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventsPage_select".
 */
export interface EventsPageSelect<T extends boolean = true> {
  heroImage?: T;
  heroTitle?: T;
  heroDescription?: T;
  upcomingEventsSectionTitle?: T;
  pastEventsSectionTitle?: T;
  ctaSectionTitle?: T;
  ctaSectionDescription?: T;
  proposeEventButtonText?: T;
  becomeSpeakerButtonText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}