/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    trainingDomains: TrainingDomain;
    partners: Partner;
    faq: Faq;
    programs: Program;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    trainingDomains: TrainingDomainsSelect<false> | TrainingDomainsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    pages: Page;
  };
  globalsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainingDomains".
 */
export interface TrainingDomain {
  id: number;
  name?: string | null;
  image?: (number | null) | Media;
  trainings?:
    | {
        name?: string | null;
        shortDescription?: string | null;
        longDescription?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        price?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  websiteUrl?: string | null;
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  name?: string | null;
  shortDescription?: string | null;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'trainingDomains';
        value: number | TrainingDomain;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainingDomains_select".
 */
export interface TrainingDomainsSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  trainings?:
    | T
    | {
        name?: T;
        shortDescription?: T;
        longDescription?: T;
        price?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  websiteUrl?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  name?: T;
  shortDescription?: T;
  longDescription?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  home?: {
    heroImages?:
      | {
          heroImage?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    heroTitle?: string | null;
    heroDescription?: string | null;
    aboutUsSectionTitle?: string | null;
    aboutUsSectionDescription?: string | null;
    aboutUsSectionButtonText?: string | null;
    aboutUsSectionImages?:
      | {
          heroImage?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    ourPartnersSectionTitle?: string | null;
    ourPartnersSectionDescription?: string | null;
    ourTrainingsSectionTitle?: string | null;
    ourTrainingsSectionDescription?: string | null;
    faqSectionTitle?: string | null;
    faqSectionDescription?: string | null;
    contactUsSectionTitle?: string | null;
    contactUsSectionDescription?: string | null;
    contactUsSectionImage?: (number | null) | Media;
    contactUsSectionButtonText?: string | null;
    newsletterSectionTitle?: string | null;
    newsletterSectionDescription?: string | null;
  };
  about?: {
    heroImage?: (number | null) | Media;
    heroTitle?: string | null;
    heroDescription?: string | null;
    heroButtonText?: string | null;
    aboutUsSectionTitle?: string | null;
    aboutUsSectionDescription?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    aboutUsGallerySectionTitle?: string | null;
    aboutUsGallerySectionDescription?: string | null;
    aboutUsGallerySectionImages?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  trainings?: {
    heroImage?: (number | null) | Media;
    heroTitle?: string | null;
    heroDescription?: string | null;
    heroButtonText?: string | null;
    trainingsSectionTitle?: string | null;
    trainingsSectionDescription?: string | null;
  };
  contact?: {
    heroImage?: (number | null) | Media;
    heroTitle?: string | null;
    heroDescription?: string | null;
  };
  faq?: {
    heroImage?: (number | null) | Media;
    heroTitle?: string | null;
    heroDescription?: string | null;
    heroButtonText?: string | null;
    faqSectionTitle?: string | null;
    faqSectionDescription?: string | null;
  };
  programs?: {
    heroImage?: (number | null) | Media;
    heroTitle?: string | null;
    heroDescription?: string | null;
    heroButtonText?: string | null;
    programsSectionTitle?: string | null;
    programsSectionDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  home?:
    | T
    | {
        heroImages?:
          | T
          | {
              heroImage?: T;
              id?: T;
            };
        heroTitle?: T;
        heroDescription?: T;
        aboutUsSectionTitle?: T;
        aboutUsSectionDescription?: T;
        aboutUsSectionButtonText?: T;
        aboutUsSectionImages?:
          | T
          | {
              heroImage?: T;
              id?: T;
            };
        ourPartnersSectionTitle?: T;
        ourPartnersSectionDescription?: T;
        ourTrainingsSectionTitle?: T;
        ourTrainingsSectionDescription?: T;
        faqSectionTitle?: T;
        faqSectionDescription?: T;
        contactUsSectionTitle?: T;
        contactUsSectionDescription?: T;
        contactUsSectionImage?: T;
        contactUsSectionButtonText?: T;
        newsletterSectionTitle?: T;
        newsletterSectionDescription?: T;
      };
  about?:
    | T
    | {
        heroImage?: T;
        heroTitle?: T;
        heroDescription?: T;
        heroButtonText?: T;
        aboutUsSectionTitle?: T;
        aboutUsSectionDescription?: T;
        aboutUsGallerySectionTitle?: T;
        aboutUsGallerySectionDescription?: T;
        aboutUsGallerySectionImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  trainings?:
    | T
    | {
        heroImage?: T;
        heroTitle?: T;
        heroDescription?: T;
        heroButtonText?: T;
        trainingsSectionTitle?: T;
        trainingsSectionDescription?: T;
      };
  contact?:
    | T
    | {
        heroImage?: T;
        heroTitle?: T;
        heroDescription?: T;
      };
  faq?:
    | T
    | {
        heroImage?: T;
        heroTitle?: T;
        heroDescription?: T;
        heroButtonText?: T;
        faqSectionTitle?: T;
        faqSectionDescription?: T;
      };
  programs?:
    | T
    | {
        heroImage?: T;
        heroTitle?: T;
        heroDescription?: T;
        heroButtonText?: T;
        programsSectionTitle?: T;
        programsSectionDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}